image: node:latest

cache:
  paths:
    - node_modules/

build:
    script:
      - yarn install --frozen-lockfile
      - yarn build
    artifacts:
      paths:
        - build
      expire_in: 1 week

