image: node:latest

cache:
  paths:
    - node_modules/

build:
    script:
      - yarn install --frozen-lockfile
      - yarn build
    artifacts:
      paths:
        - build
      expire_in: 1 week

deploy:
  stage:  deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client bash rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  environment:
    name: production
    url: chat.innatical.com
  script:
    - rsync -hrvz --delete --exclude=_ -e "ssh" --progress build/ gitlab_deploy@10.0.0.1:/var/www/chat.innatical.com
  only:
    - master
