image: node:latest

build:
  stage: build
  before_script:
    - curl -sL https://sentry.io/get-cli/ | bash
  script:
    - echo "$NPMRC" > .npmrc
    - yarn install --frozen-lockfile
    - export VITE_APP_VERSION=`sentry-cli releases propose-version`
    - yarn build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  cache:
    paths:
      - node_modules/

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client bash rsync curl bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - curl -sL https://sentry.io/get-cli/ | bash
  environment:
    name: production
    url: octii.chat
  script:
    - export VITE_APP_VERSION=`sentry-cli releases propose-version`
    - sentry-cli releases new "$VITE_APP_VERSION"
    - sentry-cli releases set-commits "$VITE_APP_VERSION" --auto
    - sentry-cli releases finalize "$VITE_APP_VERSION"
    - rsync -hrvz --delete --exclude=_ -e "ssh" --progress dist/ octii-admin@185.187.169.100:/var/www/octii.chat
  only:
    - master
